# Generated by Django 4.2.18 on 2025-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('white', 'White'), ('blue', 'Blue'), ('black', 'Black'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Ornge'), ('yellow', 'Yellow'), ('red', 'Red'), ('grey', 'Grey'), ('brown', 'Brown'), ('silver', 'Silver'), ('gold', 'Gold')], default='white', max_length=50),
        ),
    ]
